spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: "${DATASOURCE_PASSWORD}"
        url: jdbc:mysql://localhost:3306/pet_hotel_db?createDatabaseIfNotExist=true

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                format_sql: true

cloudinary:
    cloud-name: itraykov
    api-key: "${CLOUDINARY_API_KEY}"
    api-secret: "${CLOUDINARY_API_SECRET}"